### ISSUE TITLE
2026.2.1: Error setting up entry Somneo for somneo

### ISSUE THREAD

**Issue by idl0r** [theneweinstein/somneo#83]
Hi,

looks like https://github.com/theneweinstein/somneo/commit/7257b78dc3d83a7e860ac10be25ff05a58ba7eaa broke something:

```
Protokolldetails (FEHLER)
Logger: homeassistant.config_entries
Quelle: config_entries.py:762
Erstmals aufgetreten: 14:53:43 (1 Vorkommnis)
Zuletzt protokolliert: 14:53:43

Error setting up entry Somneo for somneo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 762, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/somneo/__init__.py", line 41, in async_setup_entry
    coordinator = SomneoCoordinator(hass, host, use_session=use_session)
  File "/config/custom_components/somneo/__init__.py", line 105, in __init__
    self.somneo = Somneo(
                  ~~~~~~^
        host,
        ^^^^^
    ...<2 lines>...
        read_timeout=20.0
        ^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: Somneo.__init__() got an unexpected keyword argument 'connect_timeout'
```

**Comment by idl0r** [comment]
That's a complete different problem at least.

**Comment by theneweinstein** [comment]
Did you try to unpower the Somneo and repower it after a minute of so? Sometimes it doesn't want to respond anymore and this sometimes fixes the issue.

**Comment by RYgosse** [comment]
Same problem as ArLo69 here after upgrading to 2026.2.2:

2026.2.2 gives me this error
Instellen mislukt, wordt opnieuw geprobeerd: HTTPSConnectionPool(host='xxx.xxx.xxx.xxx', port=443): Max retries exceeded with url: /di/v1/products/1/wusrd (Caused by ReadTimeoutError("HTTPSConnectionPool(host='xxx.xxx.xxx..xxx', port=443): Read timed out. (read timeout=2.0)"))
IP is correct (xxx-ed out here)

Only hard resetting the device fixes the connection for a short while after which it drops off again. Will revert to an earlier version to check if this solves the issue.

**Comment by RYgosse** [comment]
After a while drops off with the following error:

Logger: homeassistant
Bron: custom_components/somneo/light.py:55
integratie: Philips Somneo (documentatie, problemen)
Eerst voorgekomen: 11 maart 2026 om 23:11:58 (4 gebeurtenissen)
Laatst gelogd: 00:30:10

Error doing job: Task exception was never retrieved (task: None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 296, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 575, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 202, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/config/custom_components/somneo/light.py", line 55, in _handle_coordinator_update
    self._attr_is_on = self.coordinator.data["light_is_on"]
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by davidjrea** [comment]
Leaving these top-of-my head notes here in case useful.

I was having a similar https connection error issue. Had a conversation with Gemini and got the following suggestion:

1) Unplugged the wakeup light for 5- 8 min. Reasoning was something about a security lock out (I was having mDNS reflection issues, unrelated...I think). Evidence was trying to connect to some suddirectory from the device IP was refused (https://<ipaddress>/di/v1/products/1/device).

2) Uninstall and reinstall the Somneo HAC. I have added mine manually because I couldn't find it in the HACS store. So I deleted the code and readded it.

3)  Restart home assistant (not just reload the YAML)

It's been working fine since Saturday.

HA 2026.2
Somneo: whatever the latest was on Saturday.

**Comment by theneweinstein** [comment]
To be honest, I don't know what the issue is here. I'm not sure if anyone who has the issue could have a look into it to see how to solve it.

**Comment by ArLo69** [comment]
Indeed powering down the Somneo for more than five minutes solved the issue for me.
To be sure I did a system restart for HA while the Somneo was down. 
Weird that an older version of the integration does not trigger the problem.

I found similar errors for a ring doorbell where a corrupted config due to a power outage was the cause. That supports the findings of David

**Comment by ArLo69** [comment]
Yesterday, I had this problem after a normal restart and not after an update.
I think I have a clue to the circumstances when it happens.
I have three alarms set with different times. Each for getting up to work at different offices. About once every two or three weeks I change the days for each of them according to which day I go to which office.

I have a strong feeling that this error occurs when I have been changing my alarms. Maybe this is something others can take note of or test with in attempt to find the cause for this problem.
