### ISSUE TITLE
v2026.2.1 broken

### ISSUE THREAD

**Issue by NorbertHD** [theneweinstein/somneo#81]
After upgrading to v2026.2.1 the integration doesn't work anymore.
The error in the log is:

```
2026-02-26 22:39:19.829 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Somneo for somneo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 769, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/somneo/__init__.py", line 41, in async_setup_entry
    coordinator = SomneoCoordinator(hass, host, use_session=use_session)
  File "/config/custom_components/somneo/__init__.py", line 105, in __init__
    self.somneo = Somneo(
                  ~~~~~~^
        host,
        ^^^^^
    ...<2 lines>...
        read_timeout=20.0
        ^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: Somneo.__init__() got an unexpected keyword argument 'connect_timeout'
```

**Comment by NorbertHD** [comment]
I'm using Home Assistant 2026.3.0b1. This version uses now Python 3.14. Perhaps Python 3.14 keyword parameters are now more strictly?
