### ISSUE TITLE
ImportError: cannot import name 'FM_PRESETS' from 'pysomneo' (/usr/local/lib/python3.13/site-packages/pysomneo/__init__.py)

### ISSUE THREAD

**Issue by snattack** [theneweinstein/somneo#69]
In latest **HA 2025.1** the integration fails to load, with the following error:

```
  File "/config/custom_components/somneo/select.py", line 9, in <module>
    from pysomneo import FM_PRESETS
ImportError: cannot import name 'FM_PRESETS' from 'pysomneo' (/usr/local/lib/python3.13/site-packages/pysomneo/__init__.py)
```

Commenting out the following lines in `select.py` work as a workaround, but it breaks other things it seems.

```
9 from pysomneo import FM_PRESETS


90  @property
91   def options(self) -> list:
92        """Return a set of selectable options."""
93        return [item.replace(" ", "_") for item in self.coordinator.somneo.dusk_sound_themes] + [item.replace(" ", "_") for item in FM_PRESETS]
```

Any ideas?

Device: ESP32 HF367x

**Comment by theneweinstein** [comment]
Did it work before, for me it works fine in 2025.1? Are you running HA core? Previous someone had a similar problem and resolved it by reinstalling the custom component.
